[package]
name = "baud"
version = "0.1.0"
edition = "2024"
description = "A modern, lightweight, blazing-fast serial terminal for debugging IoT devices."
license = "MIT"
repository = "https://github.com/bkrajendra/Baud"

[dependencies]
chrono = { version = "0.4.45", default-features = false, features = ["clock"] }
eframe = "0.36.1"
egui = "0.36.1"
image = { version = "0.25.10", default-features = false, features = ["png"] }
serialport = "4.9.0"

[build-dependencies]
ico = "0.5.0"
image = { version = "0.25.10", default-features = false, features = ["png"] }
winresource = "0.1.31"
